package com.work.model;

public class Goods_type {
    private Long gt_id;

    private String introduction;

    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbggenerated
     */
    public Goods_type(Long gt_id, String introduction, String name) {
        this.gt_id = gt_id;
        this.introduction = introduction;
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbggenerated
     */
    public Goods_type() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_type.gt_id
     *
     * @return the value of goods_type.gt_id
     *
     * @mbggenerated
     */
    public Long getGtId() {
        return gt_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_type.gt_id
     *
     * @param gt_id the value for goods_type.gt_id
     *
     * @mbggenerated
     */
    public void setGtId(Long gt_id) {
        this.gt_id = gt_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_type.introduction
     *
     * @return the value of goods_type.introduction
     *
     * @mbggenerated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_type.introduction
     *
     * @param introduction the value for goods_type.introduction
     *
     * @mbggenerated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_type.name
     *
     * @return the value of goods_type.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_type.name
     *
     * @param name the value for goods_type.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }
}