package com.work.model;

import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.List;
@Table(name = "goods_type")
public class Goods_type {
    private Integer gt_id;

    private String introduction;

    private String name;
    @Transient
    private List<Goods> goodsList;

    @Override
    public String toString() {
        return "Goods_type{" +
                "gt_id=" + gt_id +
                ", introduction='" + introduction + '\'' +
                ", name='" + name + '\'' +
                ", goodsList=" + goodsList +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbggenerated
     */
    public Goods_type(Integer gt_id, String introduction, String name) {
        this.gt_id = gt_id;
        this.introduction = introduction;
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbggenerated
     */
    public Goods_type() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_type.gt_id
     *
     * @return the value of goods_type.gt_id
     *
     * @mbggenerated
     */
    public Integer getGtId() {
        return gt_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_type.gt_id
     *
     * @param gt_id the value for goods_type.gt_id
     *
     * @mbggenerated
     */
    public void setGtId(Integer gt_id) {
        this.gt_id = gt_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_type.introduction
     *
     * @return the value of goods_type.introduction
     *
     * @mbggenerated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_type.introduction
     *
     * @param introduction the value for goods_type.introduction
     *
     * @mbggenerated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_type.name
     *
     * @return the value of goods_type.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_type.name
     *
     * @param name the value for goods_type.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    public Integer getGt_id() {
        return gt_id;
    }

    public void setGt_id(Integer gt_id) {
        this.gt_id = gt_id;
    }

    public List<Goods> getGoodsList() {
        return goodsList;
    }

    public void setGoodsList(List<Goods> goodsList) {
        this.goodsList = goodsList;
    }
}